# Alembic Configuration File

[alembic]
# path to migration scripts
script_location = migrations

# template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
# Uncomment the line below if you want the files to be prepended with date and time
#file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present
# defaults to the current working directory
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# as well as the filename.
# string value is passed to pytz.timezone() to determine
# the timezone to work with.
# Leave blank for migrating without timezone awareness.
# timezone =

# max length of characters to apply to the
# "slug" field when generating a migration file
# name. The default value is unlimited, which means
# this parameter is ignored.
# slug_length =

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files without
# a source .py file to be detected as revisions in the
# versions/ directory
# sourceless = false

# if true, revision files
# are written as unicode. By default they are written as str() objects
# in Python 2, unicode objects in Python 3.
# unicode_literals = false

# when set to 'true', will synchronize the versions in the
# env.py file with the one in migration files
# before_revision = false

[loggers]
keys = root,sqlalchemy.engine

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy.engine]
level = INFO
handlers =
qualname = sqlalchemy.engine

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
