/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Train3dRouteImport } from './routes/train-3d'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScenariosRouteImport } from './routes/scenarios'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PlanFactRouteImport } from './routes/plan-fact'
import { Route as MapRouteImport } from './routes/map'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DirectorRouteImport } from './routes/director'
import { Route as DigitalTwinRouteImport } from './routes/digital-twin'
import { Route as ClaimsRouteImport } from './routes/claims'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'

const Train3dRoute = Train3dRouteImport.update({
  id: '/train-3d',
  path: '/train-3d',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosRoute = ScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanFactRoute = PlanFactRouteImport.update({
  id: '/plan-fact',
  path: '/plan-fact',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectorRoute = DirectorRouteImport.update({
  id: '/director',
  path: '/director',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalTwinRoute = DigitalTwinRouteImport.update({
  id: '/digital-twin',
  path: '/digital-twin',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimsRoute = ClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/claims': typeof ClaimsRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/director': typeof DirectorRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/plan-fact': typeof PlanFactRoute
  '/reports': typeof ReportsRoute
  '/scenarios': typeof ScenariosRoute
  '/settings': typeof SettingsRoute
  '/train-3d': typeof Train3dRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/claims': typeof ClaimsRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/director': typeof DirectorRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/plan-fact': typeof PlanFactRoute
  '/reports': typeof ReportsRoute
  '/scenarios': typeof ScenariosRoute
  '/settings': typeof SettingsRoute
  '/train-3d': typeof Train3dRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/claims': typeof ClaimsRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/director': typeof DirectorRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/plan-fact': typeof PlanFactRoute
  '/reports': typeof ReportsRoute
  '/scenarios': typeof ScenariosRoute
  '/settings': typeof SettingsRoute
  '/train-3d': typeof Train3dRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/analytics'
    | '/audit'
    | '/claims'
    | '/digital-twin'
    | '/director'
    | '/login'
    | '/map'
    | '/plan-fact'
    | '/reports'
    | '/scenarios'
    | '/settings'
    | '/train-3d'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/analytics'
    | '/audit'
    | '/claims'
    | '/digital-twin'
    | '/director'
    | '/login'
    | '/map'
    | '/plan-fact'
    | '/reports'
    | '/scenarios'
    | '/settings'
    | '/train-3d'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/analytics'
    | '/audit'
    | '/claims'
    | '/digital-twin'
    | '/director'
    | '/login'
    | '/map'
    | '/plan-fact'
    | '/reports'
    | '/scenarios'
    | '/settings'
    | '/train-3d'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuditRoute: typeof AuditRoute
  ClaimsRoute: typeof ClaimsRoute
  DigitalTwinRoute: typeof DigitalTwinRoute
  DirectorRoute: typeof DirectorRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  PlanFactRoute: typeof PlanFactRoute
  ReportsRoute: typeof ReportsRoute
  ScenariosRoute: typeof ScenariosRoute
  SettingsRoute: typeof SettingsRoute
  Train3dRoute: typeof Train3dRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/train-3d': {
      id: '/train-3d'
      path: '/train-3d'
      fullPath: '/train-3d'
      preLoaderRoute: typeof Train3dRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios': {
      id: '/scenarios'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof ScenariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan-fact': {
      id: '/plan-fact'
      path: '/plan-fact'
      fullPath: '/plan-fact'
      preLoaderRoute: typeof PlanFactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/director': {
      id: '/director'
      path: '/director'
      fullPath: '/director'
      preLoaderRoute: typeof DirectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-twin': {
      id: '/digital-twin'
      path: '/digital-twin'
      fullPath: '/digital-twin'
      preLoaderRoute: typeof DigitalTwinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claims': {
      id: '/claims'
      path: '/claims'
      fullPath: '/claims'
      preLoaderRoute: typeof ClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuditRoute: AuditRoute,
  ClaimsRoute: ClaimsRoute,
  DigitalTwinRoute: DigitalTwinRoute,
  DirectorRoute: DirectorRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  PlanFactRoute: PlanFactRoute,
  ReportsRoute: ReportsRoute,
  ScenariosRoute: ScenariosRoute,
  SettingsRoute: SettingsRoute,
  Train3dRoute: Train3dRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
